#!/bin/bash
MAIN_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
PORT=8000

if [[ -f $MAIN_DIR/.python-version ]]; then
echo ".python-version located in $MAIN_DIR, it will be used to start server."
echo
elif [[ -f $MAIN_DIR/venv/bin/activate ]]; then
echo "venv detected in $MAIN_DIR, using it to run flask"
cd $MAIN_DIR/venv/bin/
. ./activate &>/dev/null 2>&1
else
echo "no python detected for this application, using the system one"
fi

cd $MAIN_DIR/app

LSOF=$(lsof -i :$PORT | sed '1d')
if [ ! "$LSOF" == "" ]; then
echo $LSOF | awk '{print $2}' | xargs kill -9 &>/dev/null 2>&1
fi

if [ "$1" == "dev" ]; then
    echo "Starting in dev mode."
    export FLASK_APP=app.py
    flask run --host 0.0.0.0 --port $PORT &> $MAIN_DIR/flask.out 2>&1 &
elif [ "$1" == "prod" ]; then
    echo "Starting wsgi."
    gunicorn --bind 0.0.0.0:$PORT wsgi:app
else
    echo "Choose starting mode:"
    echo 'For dev purpose, execute: ./start "dev"'
    echo 'For wsgi, execute: ./start "prod"'
fi
