name: Docker Image CI

on:
  push:
    branches: [ "actions-tests2" ]
  pull_request:
    branches: [ "actions-tests2" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          submodules: true
          token: ${{ secrets.CI_TOKEN }}

      - name: Install python dependencies
        run: |
          pip install -r requirements.txt

      - name: Create certificates
        run: |
          openssl req -x509 -newkey rsa:4096 -nodes -out app/cert.pem -keyout app/key.pem -days 1 -subj "/C=PL/ST=State/L=/O=/OU=/CN=localhost"


      - name: Build and Run Docker image
        run: |
          IMAGE_NAME="zostaw/multiarch-home-page"
          IMAGE_TAG="latest"
          docker build -t $IMAGE_NAME:$IMAGE_TAG .
          docker compose up -d

      - name: Create Docker Network
        run: docker network create my-network

      - name: attach to network
        run: docker network connect my-network home-page-home-page-1

      - name: Verify in next job
        run: |
          sleep 3
          docker ps

      - name: Wget localhost
        run: |
          wget --no-check-certificate --mirror --page-requisites --convert-links \
          --no-parent -P downloaded-site https://localhost:8080

      - name: Execute tests
        run: |
          docker run --network=my-network --shm-size=1g -e BROWSER=chrom -v $WORKSPACE/robot-tests:/opt/robotframework/tests:Z -v $WORKSPACE/robot-reports:/opt/robotframework/reports:Z ppodgorsek/robot-framework:latest

          #      - name: Execute tests
          #        uses: joonvena/robotframework-docker-action@v1.0
          #        with:
          #          browser: chrome

      - name: Upload test results
        uses: actions/upload-artifact@v1
        if: always()
        with:
          name: reports
          path: reports


  build:
    needs: build-and-test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          submodules: true
          token: ${{ secrets.CI_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .  # Path to the Dockerfile
          push: true
          platforms: linux/arm/v6,linux/arm/v8,linux/arm64,linux/amd64
          tags: |
            zostaw/multiarch-home-page:latest
            zostaw/multiarch-home-page:${{ github.sha }}
