name: Docker Image CI

on:
  push:
    branches: [ "actions-tests2" ]
  pull_request:
    branches: [ "actions-tests2" ]

jobs:
  build-and-run-container:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          submodules: true
          token: ${{ secrets.CI_TOKEN }}

      - name: Install python dependencies
        run: |
          pip install -r requirements.txt

      - name: Create certificates
        run: |
          openssl req -x509 -newkey rsa:4096 -nodes -out app/cert.pem -keyout app/key.pem -days 1 -subj "/C=PL/ST=State/L=/O=/OU=/CN=home-page-home-page-1"

      - name: Build and Run Docker image
        run: |
          IMAGE_NAME="zostaw/multiarch-home-page"
          IMAGE_TAG="latest"
          docker build -t $IMAGE_NAME:$IMAGE_TAG .
          docker compose up -d

  test:
    needs: build-and-run-container
    runs-on: ubuntu-latest
    steps:
    - name: wget the built website
      run: |
        wget --mirror --page-requisites --convert-links \
        --no-parent -P downloaded-site https://home-page-home-page-1:8080/

    - name: Execute tests
      uses: joonvena/robotframework-docker-action@v1.0
      with:
        browser: chrome

    - name: Upload test results
      uses: actions/upload-artifact@v1
      if: always()
      with:
        name: reports
        path: reports


  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          submodules: true
          token: ${{ secrets.CI_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .  # Path to the Dockerfile
          push: true
          platforms: linux/arm/v6,linux/arm/v8,linux/arm64,linux/amd64
          tags: |
            zostaw/multiarch-home-page:latest
            zostaw/multiarch-home-page:${{ github.sha }}
