name: Docker Image CI

on:
  push:
    branches: [ "actions-tests" ]
  pull_request:
    branches: [ "actions-tests" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Add a step to fetch GitHub modules
      - name: Checkout external modules
        run: |
          git submodule init
          git submodule update
          
      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .  # Path to the Dockerfile
          push: true
          platforms: linux/arm/v6,linux/arm/v8,linux/arm64,linux/amd64
          tags: |
            zostaw/multiarch-home-page:latest
            zostaw/multiarch-home-page:${{ github.sha }}
