name: Run Tests

on:
  push:
    branches-ignore:
      - main
  workflow_call:

jobs:
  test_page_initiation:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          submodules: true
          token: ${{ secrets.CI_TOKEN }}

      - name: Create certificates
        run: |
          #openssl req -x509 -newkey rsa:4096 -nodes -out app/cert.pem -keyout app/key.pem -days 1 -subj "/C=PL/ST=State/L=/O=/OU=/CN=localhost"
          openssl genrsa -out app/key.pem 4096
          openssl req -new -x509 -nodes -days 3600 -key app/key.pem -out app/cert.pem

      - name: Verify cert files
        run: |
          echo $PWD:
          ls -last
          echo $PWD/app/:
          ls -last app

      - name: Build and run test web
        run: |
          IMAGE_NAME="zostaw/multiarch-home-page"
          IMAGE_TAG="latest"
          docker build -t $IMAGE_NAME:$IMAGE_TAG .
          docker compose up -d

      - name: Create docker network
        run: |
          docker network create my-network
          docker network connect my-network home-page-home-page-1

      - name: Verify container
        run: |
          sleep 5
          docker container ls -a
          docker logs home-page-home-page-1

      - name: Execute tests
        run: |
          sudo mkdir -m 777 $PWD/reports
          docker run --network=my-network --shm-size=1g -e BROWSER=chrome -v ${PWD}/robot_tests:/opt/robotframework/tests:Z -v $PWD/reports:/opt/robotframework/reports:Z ppodgorsek/robot-framework:latest

      - name: Upload test results
        uses: actions/upload-artifact@v1
        if: always()
        with:
          name: reports
          path: reports

